import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import CssBaseline from '@mui/material/CssBaseline';
import AppKit from "./context/initWallet";
import CheckAuth from "./context/checkAuth";

const GoogleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppKit>
          <CheckAuth>
            <CssBaseline />
            <GoogleOAuthProvider clientId={GoogleClientId!}>

              {children}
            </GoogleOAuthProvider>
          </CheckAuth>
        </AppKit>
      </body>
    </html>
  );
}
